### ISSUE TITLE
Support word/line deletion

### ISSUE THREAD

**Issue by rlivsey** [bustlelabs/mobiledoc-kit#169]
`option`+`backspace` on OSX should delete the word to the left, this is `ctrl`+`backspace` on Windows & Linux IIRC. 

Likewise `cmd`+`backspace` on OSX should delete to the start of the line, I'm not sure what the Windows/Linux shortcut for this is…

**Comment by bantic** [comment]
Thanks for opening. This should definitely be added.

**Comment by rlivsey** [comment]
I wonder if the standard behaviour is documented anywhere, or if there are other projects which do this we can crib from. It's not a simple as "delete up to the closest whitespace character" unfortunately.

Certain non-whitespace characters (eg `:`) look to be treated as part of the word, whereas others (eg `+`) aren't:

Quick experiment results, where `|` is the cursor:
      
           before  |   after 
--------------------|-----------------------
 foo bar `|`       | foo `|`
 foo+bar `|`      | foo+`|`
 foo:bar `|`      | `|`

Possibly "just" a case of coming up with a whitelist of characters to treat as separators or not.

**Comment by bantic** [comment]
Interesting. I also found this [apple doc](https://support.apple.com/en-us/HT201236) that shows some other common movement commands.
Whitelisting word-separators seems like a fine way to go. I experimented briefly just now and can find only one other separator that is ignored like the colon is: the underscore.

**Comment by rlivsey** [comment]
Cool, that's hopefully fairly straightforward then. I'll take a stab at it tomorrow as it's probably a good task to get my head around section editing etc…

**Comment by chrisdpeters** [comment]
The same goes for `option` + `shift` + `left/right arrow` for highlighting an individual word or or `cmd` + `shift` + `left/right arrow` for highlighting a whole line.

**Comment by bantic** [comment]
the word and line cursor movements are implemented as of [v0.10.0](https://github.com/bustlelabs/mobiledoc-kit/releases/tag/v0.10.0). Supporting option-delete is in progress...
