### ISSUE TITLE
List items can be enabled, removed based on selections

### ISSUE THREAD

**Issue by mixonic** [bustlelabs/mobiledoc-kit#186]
Any list items currently under select should be toggleable.

**A list item under cursor should remove list formatting when toggled**

Content-Kit:

![](http://g.recordit.co/0coITnC1EQ.gif)

Google Docs:

![](http://g.recordit.co/2D85eWeP2Y.gif)

**Several selected sections should get list formatting when toggled, unless they already have it**

Content-Kit:

![](http://g.recordit.co/PmIddisc87.gif)

Google Docs:

![](http://g.recordit.co/RkdKmZuXEp.gif)

**Comment by bantic** [comment]
wip on https://github.com/bustlelabs/mobiledoc-kit/tree/toggle-list-sections-186
