### ISSUE TITLE
Ability to opt out of default commands/expansions

### ISSUE THREAD

**Issue by rlivsey** [bustlelabs/mobiledoc-kit#191]
Currently a number of default commands & expansions are [registered](https://github.com/bustlelabs/content-kit-editor/blob/051d267773e797f63f0a06c6290ce072506b6a75/src/js/editor/editor.js#L81-L82) these are great most of the time, but on occasions I've not wanted them and had to resort to filtering out / clearing the `editor.expansions` / `editor.keyCommands` arrays.

There are a few options I can see for customising this behaviour:

### 1 - opt out of them all 

Pass an option to opt out of the defaults:

```javascript
new Editor({
  defaultCommands: false,
  defaultExpansions: false
})
```

This isn't very granular, maybe you just don't want the header expansion but everything else is good? It's also difficult to add back the ones you want (see 3).

### 2 - pass in named list of what you want

We could give the commands names so they can be referred to externally:

```javascript
new Editor({
  commands: ["bold"],
  expansions: ["list", "heading"]
})
```

If none are supplied, then all the defaults apply.

### 3 - export the defaults

In addition / instead we could export these defaults so they are available to be used by the user in-case they want to modify them?

Eg if I want to add another expansion so hyphen `- ` also works for list instead of just `* ` then there's a [non-trivial amount of code to replicate](https://github.com/bustlelabs/content-kit-editor/blob/051d267773e797f63f0a06c6290ce072506b6a75/src/js/editor/text-expansions.js#L8-L21).

It would be much nicer if these default commands/expansions were exported or (probably even better?) their behaviour moved into `postEditor` so that they are more easily re-used?

**Comment by bantic** [comment]
@rlivsey Good thoughts here. I lean toward wanting to be able to opt out of all defaults (option 1) and then improving the API for the postEditor to make it simpler to replace an existing section with a different kind. List sections are currently more complicated to create than they ought to be.

Extracting sets of defaults also makes sense to me. A simple "markdown" set that has more expansions (in-line bolding, italicizing, linking, etc) would be neat to eventually have.

**Comment by bantic** [comment]
closing and moving discussion to #480
