### ISSUE TITLE
support for internet explorer

### ISSUE THREAD

**Issue by bantic** [bustlelabs/mobiledoc-kit#212]
Roll-up issue to track differences in IE that will need to be handled to fully support it:

  * [x] IE does not fire [`input` events](https://developer.mozilla.org/en-US/docs/Web/Events/input) on contenteditable (possible workarounds would be to use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) (IE11), polling in conjunction with key* events, using hidden input to capture text
  * [ ] hide the resize handles that IE puts on block content (like images), see [this SO question/answer](http://stackoverflow.com/questions/21864047/ie-how-to-disable-elements-selection-and-resizing-in-contenteditable-div)
  * [x] IE before "Edge" does not support `Selection#extend`. This breaks our selection logic- backwards selections without `extend` are basically impossible without implementing selections non-natively, so perhaps we will just allow them to break on IE pre-Edge.

**Comment by mixonic** [comment]
I have all tests passing and basic support for Edge. Working on IE11.

IE10 is going to be more difficult to get tests happy for, since it does not have the `insertText` command (and in theory the `input` event).

**Comment by mixonic** [comment]
IE11 also does not have `insertText`. Going to try and write a workaround for tests.

**Comment by mixonic** [comment]
https://github.com/bustlelabs/mobiledoc-kit/pull/242 fixes tests for IE Edge

**Comment by mixonic** [comment]
the resize blocks are not in IE11, so I've crossed out that item. We're a go for IE11 support in master!
