### ISSUE TITLE
Firefox throws errors after selecting-all, deleting, and then typing

### ISSUE THREAD

**Issue by vitosamson** [bustlelabs/mobiledoc-kit#215]
Steps to reproduce: open demo site in Firefox (41.0.2 on OS X 10.11.1 here), select all text, press delete, then start typing new text.

The following errors are thrown for me:
![image](https://cloud.githubusercontent.com/assets/6261065/10985297/1320abb8-83ee-11e5-9fcf-f4489035edaa.png)

The first two errors are thrown as soon as I delete the original text, and then each keypress thereafter throws another error.

**Comment by bantic** [comment]
Thanks, confirmed. the native cmd-A behavior in firefox selects the entire content-kit-editor div — other browsers only select the start of the first text node to end of final text node. This should be fairly straightforward to fix for FF.
