### ISSUE TITLE
Key commands should be matched exactly

### ISSUE THREAD

**Issue by vitosamson** [bustlelabs/mobiledoc-kit#216]
Currently if you press opt-cmd-B or ctrl-cmd-B it toggles bold, even though the key command is configured for just META+B or CTRL+B, but not both together.

**Comment by rlivsey** [comment]
Good catch, the culprit is in [`findKeyCommands` here](https://github.com/bustlelabs/content-kit-editor/blob/391878e607e9f3bc1705fdf56c1392d6d4b21a54/src/js/editor/key-commands.js#L123) where we're currently just checking for the defined keys but not checking if any others are pressed.

```javascript
return (modifier && key.hasModifier(modifier)) || (!modifier && !key.hasAnyModifier());
```

**Comment by bantic** [comment]
I think maybe a bitmask for the key modifiers would simplify this? I may take a stab at this later today.
