### ISSUE TITLE
Add Mobiledoc version support to mobiledoc parser and renderer

### ISSUE THREAD

**Issue by mixonic** [bustlelabs/mobiledoc-kit#233]
We're shortly to introduce atoms and v0.3 of the mobiledoc format in https://github.com/bustlelabs/mobiledoc-kit/pull/226. To ensure we have a smooth iteration path for these changes, the mobiledoc parser and renderer should be able to support multiple versions.

**Comment by bantic** [comment]
Somewhat related: https://github.com/bustlelabs/mobiledoc-dom-renderer/issues/13 and https://github.com/bustlelabs/mobiledoc-html-renderer/issues/10. The dom and html renderers will currently throw with a useful error message if they encounter an unknown version of mobiledoc (they only know about v 0.2.0 at the moment)

**Comment by bantic** [comment]
fixed by #241
