### ISSUE TITLE
Question: Know of any mobiledoc editors written in React?

### ISSUE THREAD

**Issue by aaronshaf** [bustlelabs/mobiledoc-kit#243]

**Comment by mixonic** [comment]
@aaronshaf none at this moment. Whipping something up should not be too difficult though :-)

Closing for now but very open if someone else wants to comment here.

**Comment by joshfrench** [comment]
This has a _long_ way to go before it's useable, but we're working on one!

https://github.com/upworthy/react-mobiledoc-editor
