### ISSUE TITLE
Copying/pasting inside list elements doesn't work

### ISSUE THREAD

**Issue by fbarl** [bustlelabs/mobiledoc-kit#249]
I first noticed it in my app where I'm using `Mobiledoc-kit`, but it's easy to reproduce it on http://bustlelabs.github.io/mobiledoc-kit/demo/ as well.

Say I have a paragraph 'X' and a list with a single element 'Y'. I select 'X', copy it, then I select 'Y' and paste over it. That throws an error `Uncaught TypeError: Cannot read property 'renderNode' of undefined` for me on Chrome. Even when the cursor is collapsed, pasting inside `<li>` elements doesn't seem to work and neither does copying, which throws a different error for me: `Uncaught Error: Cannot set section tagName to li`.

I also tried Firefox, and similar thing happens, so the problem seems to be general. I was surprised that nobody has reported it since it seems this problem's been there for a while. :) Do you think there's an easy fix for it or it would require some deeper refactoring?

Thanks!

**Comment by mixonic** [comment]
> I was surprised that nobody has reported it since it seems this problem's been there for a while.

Ha! The community of users is still pretty small :-) I'm not surprised if we have a bug. Thanks for taking the time to report this, Cory or I will take a look shortly.
