### ISSUE TITLE
Hitting "Enter" selects the text

### ISSUE THREAD

**Issue by YoranBrondsema** [bustlelabs/mobiledoc-kit#261]
I don't know if this is intended behavior but I noticed a difference in the new 0.7.1 release. When you hit "Enter" in the middle of a line containing text, it selects the part of the text between where you intended the line break and the end of the line.

These screenshots will make it clearer.

BEFORE: the cursor is between the "e" and the "d" in the word "Mobiledoc".
![before](https://cloud.githubusercontent.com/assets/1374412/11763808/1cd16bd0-a0f8-11e5-970c-f961c516813e.png)

AFTER: I hit Enter and the text gets selected
![after](https://cloud.githubusercontent.com/assets/1374412/11763809/241bdad8-a0f8-11e5-9644-446c31944d38.png)

**Comment by mixonic** [comment]
Thanks @YoranBrondsema. Seems like a regression.
