### ISSUE TITLE
use Text parser for plaintext pasting

### ISSUE THREAD

**Issue by bantic** [bustlelabs/mobiledoc-kit#263]
#262 adds code to fall back to using the text/plain paste data when text/html is not available, but the plaintext is still parsed into mobiledoc with the HTML parser. There should be a text parser instead that can do things like translate linebreaks into multiple sections, etc.

**Comment by bantic** [comment]
@YoranBrondsema I'm going to tackle this today...Let me know if you already looked at it, otherwise hopefully I can finish it up today.

**Comment by YoranBrondsema** [comment]
@bantic I haven't, please go ahead!
