### ISSUE TITLE
possible to insert card into list

### ISSUE THREAD

**Issue by bantic** [bustlelabs/mobiledoc-kit#272]
It is possible to (incorrectly) insert a card (or non-markerable) into a list. To reproduce, in the demo:

  * create a 3-item list
  * delete the text in the middle item, leave the cursor there
  * click the "add image" button
  * the image is rendered in the editor in between the list items. In the dom-rendered output and in the mobiledoc it is after the list section. The correct behavior is to break the list in two and insert the image between the pre- and post- lists.

Shot of the editor:
![image](https://cloud.githubusercontent.com/assets/2023/11855508/afba7e3c-a418-11e5-9199-cfb53ae4e436.png)

Shot of the DOM for the editor:
![image](https://cloud.githubusercontent.com/assets/2023/11855551/f480947a-a418-11e5-8878-07bd24488bd6.png)

There appear to be two bugs:
  * The editor-dom renderer is rendering the card div in the list
  * The "add image" button is adding the image after the list instead of splitting the list and adding it between

Fixing the latter bug may obviate the former.

**Comment by mixonic** [comment]
This issue is still present, however now the behavior is that the image card does not show in the editor, but does get into the AST.

**Comment by bantic** [comment]
`Editor#insertCard` does the appropriate thing now when the cursor is positioned in a list. The card is inserted after the list.
