### ISSUE TITLE
Prepending list before a paragraph deletes the list

### ISSUE THREAD

**Issue by YoranBrondsema** [bustlelabs/mobiledoc-kit#280]
When inserting a digit followed by a period before a paragraph, the list is created but the paragraph is deleted. See the screencast.

![screencast](https://cloud.githubusercontent.com/assets/1374412/12081162/3864f650-b250-11e5-9544-cf5f5fc3b248.gif)

**Comment by bantic** [comment]
@YoranBrondsema Thanks for reporting. I have a fix in #282 that avoids deleting the paragraph, but it also prevents the behavior I'm assuming you're expecting here, which is that typing "1. " at the start of a paragraph turns the remainder of that paragraph into a list item. That will take a little more work with the text-expansion code, so I'm going to open another issue to track it.

**Comment by YoranBrondsema** [comment]
@bantic Thanks for the fix! I think your fix offers better behavior cause there's always a workaround for users that expected a list, i.e. select the text and turn it into a list. For text being deleted there's not an easy workaround :-).
