### ISSUE TITLE
unlinking should not prompt for url

### ISSUE THREAD

**Issue by bantic** [bustlelabs/mobiledoc-kit#295]
When selecting linked text and unlinking (type cmd-K or click "link" button), the editor prompts for a url that is subsequently ignored. The editor should unlink the text without showing a prompt.

**Comment by mixonic** [comment]
I cannot find an issue for it, but I think this should likely be solved in https://github.com/bustlelabs/ember-mobiledoc-editor

**Comment by bantic** [comment]
@mixonic The link button from ember-mobiledoc-editor does the correct behavior (it unlinks when the selected text is a link). This appears to be limited to mobiledoc-kit's "cmd-K" key command.
