### ISSUE TITLE
Formatting text deletes it

### ISSUE THREAD

**Issue by dtetto** [bustlelabs/mobiledoc-kit#299]
We’ve had several reports over time of formatting (bold, italic, or links) removing the contents instead. Today and yesterday (on `0.8.0-beta.3`) from two users:

> “tried italicizing in this post [...] and it deleted the text”

> “tried bolding in this piece: [...] and it just deleted the entire text
> i refreshed the page and now it’s there, but every time i try to bold, it deletes
> i even tried clicking the “B” instead, and still happens
> mac, chrome, and was trying to bold the next at the top, but seems once i added a space between the existing text and what i was trying to add, i could bold without an issue
> but for some reason whenever i tried to do it in the text it was erasing the text in its entirety”

**Comment by bantic** [comment]
probably related to #306
