### ISSUE TITLE
Extendable markup section tag names

### ISSUE THREAD

**Issue by fusion2004** [bustlelabs/mobiledoc-kit#342]
The same way that `pull-quote` has been added as a tag name that maps to `<div class="pull-quote">`, it would be excellent to be able to configure additional markup section tag names that are handled in the same way.

**Comment by fusion2004** [comment]
Also, if this is a wanted feature, I would be happy to implement (across here, the ember editor, the dom renderer, and anything else that needs it) - I just need some direction. Mainly, where would such a config go? On the editor object?

**Comment by gdub22** [comment]
@fusion2004 is this what you're looking for? https://github.com/bustlelabs/mobiledoc-dom-renderer#sectionelementrenderer

**Comment by fusion2004** [comment]
Not really: The problem with that is you can only customize the rendering of one of those allowed tag names as listed in the comment in that example.

And I believe there's an inconsistency / bug with how the dom renderer output pull-quote right now.
The editor outputs `<tagName>` for everything but `pull-quote`, which outputs `<div class="pull-quote">`. The dom renderer only ever outputs the first unless you specify a section element renderer, but this is easy enough to fix: https://github.com/fusion2004/mobiledoc-dom-renderer-many-divs/commit/752aa1513b6f8985c2c05352b1835356ae380939

What I'm proposing is a universal way to configure additional tag names that behave like `pull-quote`.

**Comment by bantic** [comment]
@fusion2004 Thanks for raising this. Do you have a set of additional markup section types already in mind?

One of the goals for the mobiledoc format is to encourage interoperability (i.e. have it be a "portable"/"shareable" format — in an ideal future there'd be alternative editors that output mobiledoc, allowing developers to choose the "editor du jour" but still retain the benefits of the constrained mobiledoc format, allowing them to continue rendering mobiledoc on their site no matter which editor it was generated with). 

Extendable markup would potentially couple a mobiledoc to its editor and renderer — i.e., your mobiledoc, with its custom tagNames, would be incompatible with my site because my renderer doesn't know (and can't anticipate) the custom tagNames your mobiledocs might use.

That said, I would like to see a way to allow something like what you're proposing, especially if there can be a good path to allowing the extensibility without the potential fragmentation of renderers. Falling back to `<div class='unknownTagname'` might be the pragmatic solution here.

**Comment by bantic** [comment]
> And I believe there's an inconsistency / bug with how the dom renderer outputs pull-quote right now.

Yes, I think you're right...looking into that now.

**Comment by fusion2004** [comment]
The specific issue I ran into was wanting to be able to specify that a markup section is left-, center-, or right-aligned. I wanted to add a class so I could style it like that.

I think `pull-quote` has the issues you've mentioned as well, but I'm not sure it's a big problem since it just outputs a div with a class. To me, the fallback is that a markup section just ends up with default rendering (since a client just wouldn't know what special thing to do with it, in the case of DOM/html rendering it adds a class that if the client doesn't add css for, just renders as any div on the page would.

**Comment by bantic** [comment]
@fusion2004 Thanks for sharing that use case. That makes sense. I still have some concern that allowing any arbitrary metadata/tagName would lead to potential harmful ambiguity in rendering. Falling back to `<div class="center-aligned">` loosely couples the renderer to your CSS (I'm aware that in this case not a lot of structural information would be lost if the text weren't properly centered, though), which also further couples it to HTML/DOM. A presentation-oriented (as opposed to semantic) tagName also potentially makes the mobiledoc json less portable to other non-html/dom rendering contexts (iOS, Android, a PDF renderer). Seems like this may be more of an academic than practical distinction, though. 

Feel free to ping me directly on [gitter](https://gitter.im/bustlelabs/mobiledoc-kit) to discuss. I'd like to find a way to accommodate what you are trying to do.

**Comment by chrisdpeters** [comment]
I'd like to see these tags added to the allowed list:

- `h4`
- `h5`
- `h6`
-  `pre`

I could see there being arguments against `pre`, but I could also see that being useful across renderers, of which could decide how they want to handle blocks of pre-formatted text.

Are there any reasons to avoid `h4`-`h6` based on some of the clients that would potentially have renderers?

**Comment by bantic** [comment]
@chrisdpeters h4-h6 definitely seem worthwhile, happy to take a PR (or I will add them later). I am uncertain if `pre` may introduce native browser contenteditable rendering quirks, but I imagine it is probably not an issue.

**Comment by mixonic** [comment]
We're tracking new section tags here: https://github.com/bustlelabs/mobiledoc-kit/issues/451#issuecomment-258938244 and the [1.0 roadmap](https://docs.google.com/document/d/1Tn3XdADu50Q0VStF5sIeUqlEDWqRJRX5-ZFwUKJ4ZS8/edit) specifies we will be adding a few new markups in that timeline as well.

For reasons @bantic describes above and we [discuss in the roadmap](https://docs.google.com/document/d/1Tn3XdADu50Q0VStF5sIeUqlEDWqRJRX5-ZFwUKJ4ZS8/edit?disco=AAAAAvl76QU) hesitancy remains about adding support for 100% arbitrary section and markup types.

I'm going to close this for now as it seems mostly related to the 100% custom case at this time. Let me know if I've missed anything!

**Comment by sohara** [comment]
@mixonic Short of allowing arbitrary section types, would there be a possibility of adding support the the `section` tag name? Given that is it more semantic than presentational?
