### ISSUE TITLE
Position#move isn't available on blank position

### ISSUE THREAD

**Issue by rlivsey** [bustlelabs/mobiledoc-kit#344]
If the editor [handles a cursor key](https://github.com/bustlelabs/mobiledoc-kit/blob/c5292360ae2c8434abc4f47b293f4700891687ff/src/js/editor/editor.js#L643) when the editor doesn't have focus, then `editor.cursor.offsets` [returns a blank range](https://github.com/bustlelabs/mobiledoc-kit/blob/c5292360ae2c8434abc4f47b293f4700891687ff/src/js/utils/cursor.js#L62), with blank position objects. These blank positions don't have a `move` method and sadness occurs:

<img width="541" alt="screenshot 2016-03-16 00 03 18" src="https://cloud.githubusercontent.com/assets/3740/13798084/a8077120-eb0a-11e5-8a4a-34a2611b59af.png">

Should we just put a guard checking that `this.cursor.hasCursor()` at the top of [`handleKeydown`](https://github.com/bustlelabs/mobiledoc-kit/blob/c5292360ae2c8434abc4f47b293f4700891687ff/src/js/editor/editor.js#L624)?

**Comment by bantic** [comment]
@rlivsey Yes, that's a good catch. Exiting early on no cursor sounds like the right move. I will address this soon, but happy to take a PR in the meantime.

**Comment by bantic** [comment]
I'm looking at this and will fix it today
