### ISSUE TITLE
StackOverflow tag/channel

### ISSUE THREAD

**Issue by lessless** [bustlelabs/mobiledoc-kit#370]
Hello peeps,

thanks for your efforts to bring sanity in content editing on the web and I believe at the certain point, with more integrations & interest to the project, there will be a need for a support  place, like a StackOverflow "channel".

Personally, I don't use it that much to have enough points to  create a new tag, but if you agree with that idea I promise to contribute a first question there :) 

Cheers!

**Comment by bantic** [comment]
@lessless Great idea. Will you create a StackOverflow question for the question you asked in Gitter? I'll add the mobiledoc-kit tag to it. :)

**Comment by bantic** [comment]
If you link to the SO question here I'll close this and add the tag.

**Comment by lessless** [comment]
Thank you! Here it is http://stackoverflow.com/questions/36854594/how-to-reproduce-medium-com-editors-embed-media-button-with-mobiledoc-kit 

I think it'll be worthwhile to mention that channel in the project readme so people will know where to address questions not related to the project development.

Cheers!

**Comment by bantic** [comment]
@lessless thanks! I've answered the SO question and added the `mobiledoc-kit` tag to it. I'll add a pointer to this in the readme, too.
