### ISSUE TITLE
Add the ability to create new renderers for serialization.

### ISSUE THREAD

**Issue by Ondoher** [bustlelabs/mobiledoc-kit#371]
We have our own markup format for rich content, and it would be great if we could register our own parser for serialization.

**Comment by bantic** [comment]
@Ondoher Would it work for you to translate the mobiledoc into your own format?
Or are you talking about parsing your format into mobiledoc to pass into an editor?

**Comment by Ondoher** [comment]
I was specifically looking at how serialize takes a parameter that can be one of three values. But then I noticed that there is already a mechanism to write external parsers, I think this is a non issue.
