### ISSUE TITLE
Support for tables in the editor

### ISSUE THREAD

**Issue by Ondoher** [bustlelabs/mobiledoc-kit#372]
This might be doable with a card, but it would be cooler to handle it more like ul/li

**Comment by bantic** [comment]
Thanks for this suggestion! Tables could be super handy in some environments, but they run counter to the organizational structure of mobiledoc's internal format and cursor-comprehension strategy at the moment. It would certainly be nice to have but isn't on the roadmap for mobiledoc-kit yet.
