### ISSUE TITLE
The end and home keys appear to change selection, but really don't.

### ISSUE THREAD

**Issue by Ondoher** [bustlelabs/mobiledoc-kit#377]
This is pretty major functionality to leave out. It makes the editor unusable. Which is a shame.

**Comment by bantic** [comment]
@Ondoher Thanks for this bug report. What browser and OS do you use?

**Comment by bantic** [comment]
@Ondoher I've deployed the fixed code to the [demo](http://bustlelabs.github.io/mobiledoc-kit/demo/). Can you try it there? (May need a hard refresh.) Thanks.

**Comment by Ondoher** [comment]
Works like a charm! Thanks.
