### ISSUE TITLE
Programmatically place cursor inside Section and select Section/Atom/Card

### ISSUE THREAD

**Issue by martinklepsch** [bustlelabs/mobiledoc-kit#405]
I'd like to be able to do things like
- focus a given section (begin, end, custom index)
- select a given section, card or atom

Are there any built in utilities that can help with this?

**Comment by bantic** [comment]
@martinklepsch I'm sorry this lingered for so long!

Yes, the `editor.selectRange` method is used for both of the cases above.
`selectRange` accepts a [Mobiledoc-Kit `Range`](http://bustlelabs.github.io/mobiledoc-kit/demo/docs/Range.html) which is constructed of a head and tail [`Position`](http://bustlelabs.github.io/mobiledoc-kit/demo/docs/Position.html).

To focus at a position, use `selectRange` with a collapsed range (head position === tail position).

E.g., if you have a post with 3 sections and want to put the cursor after the 4th character in the 2nd section:
```javascript
let section = editor.post.sections.objectAt(1); // 0-indexed
let offset = 4;
let range = MobiledocKit.Range.create(section, 4); // accepts `headSection`, `headOffset`, [`tailSection`], [`tailOffset`]
editor.selectRange(range);
```

To select the entire 2nd section:
```javascript
let section = editor.post.sections.objectAt(1);
let range = new MobiledocKit.Range(section.headPosition(), section.tailPosition()); // accepts `headPosition`, `tailPosition`
editor.selectRange(range);
```

To select an atom, you would use its offset in the section (atoms have width of 1). For example, if the text of the second section is `"abc<atom>def"` you can select it like so:
```javascript
let section = editor.post.sections.objectAt(1);
let range = MobiledocKit.Range.create(section, 3, section, 4);
editor.selectRange(range);
```
