### ISSUE TITLE
Using CMD+DownArrow produces unexpected results

### ISSUE THREAD

**Issue by cknific** [bustlelabs/mobiledoc-kit#408]
With your cursor on line 1, hit CMD+DownArrow to go to the bottom of the editor. Start typing. The cursor jumps back to where you were on Line 1.

![8f1e05e8-1b70-11e6-8f8a-1baa7b704424](https://cloud.githubusercontent.com/assets/903898/15478405/e09e9410-20ce-11e6-8d60-53f5bc9ceecb.gif)

**Comment by bantic** [comment]
fixed in [v0.10.0](https://github.com/bustlelabs/mobiledoc-kit/releases/tag/v0.10.0)
