### ISSUE TITLE
Deleting first or last list item creates bad internal state for `didUpdatePost` callback

### ISSUE THREAD

**Issue by joshfrench** [bustlelabs/mobiledoc-kit#440]
Deleting the first or last item in a list creates a List section with `items = undefined` (instead of an empty linked list) which breaks `walkAllLeafSections` and possibly other related methods. I haven't been able to pinpoint exactly where the invalid List section is created, but it looks related to splitting the original list and operating on the resulting segments.

To reproduce:

```js
let mobiledoc = {
  "version": "0.3.0",
  "atoms": [],
  "cards": [],
  "markups": [],
  "sections": [
    [3,"ul",[
      [[0,[],0,"a"]],
      [[0,[],0,"b"]],
      [[0,[],0,"c"]]
    ]]
  ]
};
let editor = new Mobiledoc.Editor({ mobiledoc });
editor.didUpdatePost((postEditor) => {
  postEditor.editor.post.walkAllLeafSections(() => null);
});
```

Position cursor after either `a` or `c` and hit <kbd>delete</kbd> twice.

**Comment by bantic** [comment]
@joshfrench Thanks for reporting. I can reproduce this. The `didUpdatePost` callback is being called before all the changes to the postEditor have been coalesced (in its `complete()` method). Deleting parts of a list momentarily splits the list into (in this case) one blank list and one list with the remaining items (in the `complete()` method the blank list-section is cleaned up). The `walkAllLeafSections` method is choking on attempting to find the head/tail position of the blank list-section.

Does the `postDidChange` hook work for your use case instead? It gets called after all the changes are coalesced.

The `didUpdatePost` callback is intended to let developers "undo" changes before they are applied, but it may need to be reworked; calling it before changes have coalesced leads to errors like this one and misrepresents the internal state even if there are no errors.

**Comment by joshfrench** [comment]
Thanks Cory! `postDidChange` is fine for our use case here.
