### ISSUE TITLE
CTRL+K does not open URL dialogue on Windows

### ISSUE THREAD

**Issue by cknific** [bustlelabs/mobiledoc-kit#452]
Highlight text in the editor. Hit CMD/CTRL+K.

Expected: A browser dialogue will appear asking you to provide a URL, and hitting OK will produce a hyperlink with the selected text and provided URL.

CMD+K on Mac works as expected.

CTRL+K on Windows clears out the selected text.
![test](https://cloud.githubusercontent.com/assets/903898/17676688/7af05a7e-62e4-11e6-8715-859bebde32ba.gif)

I believe this is a regression. I've seen the issue on Windows 7 and Windows 10, Firefox and Chrome (latest).

**Comment by bantic** [comment]
@cknific Thanks for reporting — will get a fix out for this by tomorrow.

**Comment by bantic** [comment]
released in https://github.com/bustlelabs/mobiledoc-kit/releases/tag/v0.10.5

**Comment by cknific** [comment]
Thanks for this @bantic
