### ISSUE TITLE
Pasting text that contains a newline inside a list throws an error

### ISSUE THREAD

**Issue by YoranBrondsema** [bustlelabs/mobiledoc-kit#456]
## To reproduce ##

1. Go to the demo (https://bustlelabs.github.io/mobiledoc-kit/demo/)
2. Add a list (either unordered or ordered)
3. Copy the two lines in the "RAW Paste Data" section in http://pastebin.com/CdrMjutM and paste into the list

You would expect it to create a new list item for each line of text but instead it throws an error `Uncaught Error: Cannot insert non-list-item to list (is: markup-section)`.

![error](https://cloud.githubusercontent.com/assets/1374412/17875363/73888246-6886-11e6-807a-a5b502ab48a6.png)

**Comment by YoranBrondsema** [comment]
I figured it's because `parsePostFromText` transforms the text into paragraphs, divided by the newlines. Then it makes sense that it fails.

A solution would be to turn the parser into a "context-dependent" parser, i.e. if the cursor is in a list, then parse this particular example as list items, else as paragraphs. Any thoughts on this @bantic @mixonic?

**Comment by bantic** [comment]
@YoranBrondsema Thanks for the detailed bug description...I'm looking into it this morning.

**Comment by bantic** [comment]
Added a failing test here: https://github.com/bustlelabs/mobiledoc-kit/compare/456-fix-inserting-sections-into-list

**Comment by YoranBrondsema** [comment]
@bantic Wow, many thanks!

**Comment by bantic** [comment]
@YoranBrondsema no problem. Thank you for the detailed description!

released in [v0.10.6](https://github.com/bustlelabs/mobiledoc-kit/releases/tag/v0.10.6)
