### ISSUE TITLE
find matched section range on text input? 

### ISSUE THREAD

**Issue by eguitarz** [bustlelabs/mobiledoc-kit#458]
In callback onTextInput,
I'm trying to figure out a way to convert matched text into a range, but seems it's not easy to do so.

```
editor.onTextInput({
  match: /\*(.*)\* /,
  run(editor, matches) {
    // if there's any matched text, find the range in section.          
}
});
```

This is a feature if we want to automatically replace a text pattern into another one (e.g. auto convert `*mobile* ` to *mobile*. And it's a must for WYSIWYG markdown editor.

**Comment by bantic** [comment]
Probably the best way to do this is to find it relative to the editor's current range.
The editor's range is where the cursor currently is. When this `onTextInput` hook gets called, the cursor range will be collapsed (i.e., no text is selected, the range's head position === its tail position) directly after the " " (space) character that the user just typed.

```javascript
  editor.onTextInput({
    match: /\*(.*)\* /,
    run(editor, matches) {
      let text = matches[1]; // the text in the capture group;
      let range = editor.range;
      range = range.extend(-1 * (text.length + 2 + 1)); // extend the range backward to cover the text + the 2 "*" + 1 " "

      // make the text bold
      editor.run(postEditor => {
        let position = postEditor.deleteRange(range);
        let bold = postEditor.builder.createMarkup('strong');
        let nextPosition = postEditor.insertTextWithMarkup(position, text, [bold]);
        postEditor.insertTextWithMarkup(nextPosition, ' ', []); // insert the un-marked-up space
      });
    }
  });
```

some relevant docs:
  * [`postEditor#insertTextWithMarkup`](http://bustlelabs.github.io/mobiledoc-kit/demo/docs/PostEditor.html#insertTextWithMarkup)
  * [`postEditor#deleteRange`](http://bustlelabs.github.io/mobiledoc-kit/demo/docs/PostEditor.html#deleteRange)
  * [`Range#extend`](http://bustlelabs.github.io/mobiledoc-kit/demo/docs/Range.html#extend)

I think this addresses your question so I will close it now, but please feel free to reopen if you have a follow-up.
