### ISSUE TITLE
Pasting text that contains a newline throws an error

### ISSUE THREAD

**Issue by YoranBrondsema** [bustlelabs/mobiledoc-kit#462]
I think this is a regression introduced by #459. Inserting text with newlines inside a list works, as per the fix. However, inserting text with newlines outside of a list, for instance in an empty Mobiledoc instance, fails.

![error](https://cloud.githubusercontent.com/assets/1374412/17913617/41db042e-6950-11e6-852f-a10351985e74.png)

**Comment by bantic** [comment]
Darn, I knew that fix yesterday seemed too simple.
I will address this today and expand the test coverage for the post-insertion tests. Thanks for reporting!

**Comment by bantic** [comment]
released in [v0.10.7](https://github.com/bustlelabs/mobiledoc-kit/releases/tag/v0.10.7)
