### ISSUE TITLE
Adding 'mark' as a valid markup tagname

### ISSUE THREAD

**Issue by jrburke** [bustlelabs/mobiledoc-kit#473]
The [HTML mark element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark) allows setting aside text that has been marked, or highlighted, in some fashion.

This seems to be in the same spirit as the other tags like bold, italic, and seems particularly useful for group editing cases where someone may want to highlight some text to be changed or to get more consideration of the text.

Would it be possible to add 'mark' as a formally supported markup tagname?

Here is a hack I did in my local project to allow support:

``` javascript
import { VALID_MARKUP_TAGNAMES } from 'mobiledoc-kit/models/markup';
import tagNames from 'mobiledoc-dom-renderer/utils/tag-names';
import { normalizeTagName } from 'mobiledoc-dom-renderer/utils/dom';

VALID_MARKUP_TAGNAMES.push('mark');
const oldisValidMarkerType = tagNames.isValidMarkerType;
tagNames.isValidMarkerType = function (type) {
    if (normalizeTagName(type) === 'mark') {
        return true;
    }
    return oldisValidMarkerType(type);
};
```

But this hack is fragile, depends on some qualities of the ES module transpilation that may not hold true in native browser support, specifically altering an export of another module.

If support for 'mark' sounds like a good idea and you prefer a pull request, I am happy to do one for this repo and 'mobiledoc-dom-renderer' to add 'mark' to the appropriate arrays. If there are other repos/other renderers that might need that change, just let me know and I can do pull requests there too.

**Comment by bantic** [comment]
@jrburke Thanks for the suggestion — yes, a PR for `mark` would be happily accepted!

**Comment by mixonic** [comment]
In 1.0 planning we discussed this and decided to punt on it a bit. Highlighting text has several use cases:

* Highlight text in your own editor to make a change (bolding a selection for example, a temporary highlight in memory)
* Highlight text and that highlight is part of the final document (a persisted in Mobiledoc highlight)
* Highlighted text from another user in collaborative editing (a semi-persisted state perhaps not part of Mobiledoc)

As this space is pretty complex and we've not not tackled collaborative editing, I would like to reserve the space here for further exploration. I don't think we're ready for a `mark` markup yet.

However we are adding several other markups per [the roadmap](https://docs.google.com/document/d/1Tn3XdADu50Q0VStF5sIeUqlEDWqRJRX5-ZFwUKJ4ZS8/edit) and other issues in this repo.

Closing this for now, let me know if you think it should be re-opened! Cheers.

**Comment by jrburke** [comment]
It seems like other inline markup tags, like strong, em, could have other contextual meanings too. For my particular use case, the mark case was the persisted case, so it seemed like it fit with the other markup tags, and it was nice it was already an HTML tag for it.

But as long as 1.0 would allow adding this tag for our own local use cases in the form of the hack above, I can just use that. I also understand that would make the documents created in that app really not portable and in the spirit of the larger mobiledoc goal, but the app's doc use will be very constrained.

I apologize for not getting the PR put together after first filing. I ran into complications with getting work signoff for their open source process and some deprioritization of the work.
