### ISSUE TITLE
buggy behavior with events 

### ISSUE THREAD

**Issue by alidcastano** [bustlelabs/mobiledoc-kit#500]
Right now I have my mobiledoc saving changes when the user focuses out of the element.

I'm trying to add a separate input field for the title. But it seems that having another text area along with the editor causes buggy behavior. When I try to click on the title area, the mouse moves to the mobiledoc. 

I've tried placing the input field outside the element but that didn't change anything. And neither do the `preventDefault=false` or  `bubbles=false` options for events.

Questions:
- Is there a way to add separate action handlers (besides on-change) to the mobiledoc using this addon?
- Is there a better way to save the mobiledoc? (Using the on-change handler caused the mouse to move to the beginning on every change, which is why I resorted to 'focusOut'. But now it seems that I can't add another input field.)

**Comment by alidcastano** [comment]
Incase it helps, here's an example of my setup:
 
```
<div class="note-body" {{action 'saveNote' on='focusOut'>
  {{#mobiledoc-editor
      mobiledoc=note.body
      on-change=(action 'bodyWasUpdated')}}
      {{input value=note.title placeholder='Untitled'}}
  {{/mobiledoc-editor}}
</div>

// component.js
export default Ember.Component.extend({
  actions: {
    saveNote() { // triggered on focus out
      this.sendAction('save'); // calls saveNote function 
    },

    bodyWasUpdated(body) { // trigged on change
      this.set('note.body', body);
    }
 });

// controller.js 
  saveNote(){
      let note = this.get('model.note');
      note.set('title', note.get('title'));
      note.set('body', note.get('body'));
      note.save();
    }

**Comment by alidcastano** [comment]
Sorry, meant to post this on ember-mobiledoc-editor repository.

**Comment by bantic** [comment]
closing since this issue is now at https://github.com/bustlelabs/ember-mobiledoc-editor/issues/112
