### ISSUE TITLE
meta charset required

### ISSUE THREAD

**Issue by gdub22** [bustlelabs/mobiledoc-kit#510]
If you do not add `<meta charset="utf-8">`, the mobiledoc editor emits an `Â` for spaces.
Unsure if their is an underlying bug, or may just be worth mentioning in docs.

Minimal reproduction:
```html
<!doctype html>
<html>
  <body>
    <div id="editor"></div>
    <script src="https://unpkg.com/mobiledoc-kit@0.10.11/dist/global/mobiledoc-kit.js"></script>
    <script>
      new Mobiledoc.Editor().render(document.getElementById('editor'))
    </script>
  </body>
</html>
```
(cannot show on jsfiddle, etc. because their wrappers add the meta tag)

**Comment by mixonic** [comment]
I think we should document that Mobiledoc-Kit expects HTML to be UTF-8 and explain how to opt in to this.

**Comment by bantic** [comment]
draft.js does the same thing: https://facebook.github.io/draft-js/docs/overview.html#usage
