### ISSUE TITLE
Single line editor?

### ISSUE THREAD

**Issue by aehlke** [bustlelabs/mobiledoc-kit#519]
Is there a way to restrict the editor to a single-line input? Much like `input` vs. `textarea`.

**Comment by disordinary** [comment]
You can probably fake it by registering a key command `enter` which does nothing (and will override the existing mobiledoc-kit enter handling).
```javascript
const enterKeyCommand = {
  str: 'enter',
  run(editor) {
    // submit the form
  }
};
editor.registerKeyCommand(enterKeyCommand);
```

You'd also have to write a parser plugin to deal with pasted content. Document on both techniques is available here: https://github.com/bustlelabs/mobiledoc-kit
