### ISSUE TITLE
Sanitization of `href` values against XSS

### ISSUE THREAD

**Issue by YoranBrondsema** [bustlelabs/mobiledoc-kit#525]
When creating a markup of type `a`, no sanitization of the `href` value is done. It is therefore possible to add values that allow XSS attacks, e.g. `<a href="javascript:alert('XSS')">Click here</a>` (as an aside, note how the GitHub editor does not allow such values for `href`).

I'm not sure though where the sanitization should occur. I do think it belongs somewhere in `mobiledoc-kit` and shouldn't be up to the user. However, should the sanitization happen at the input, i.e. sanitize before the link is converted into Mobiledoc? Or should it happen at rendering. You can argue that for some renderers the sanitization doesn't change anything (e.g. the text renderer) and therefore you would "lose" unnecessary when sanitization when saving it into Mobiledoc. Realistically though, I do think most renderers (HTML, AMP?) do need the sanitization. So I'd say sanitizing at the input.

What are your thoughts?

**Comment by mixonic** [comment]
IMO it should almost certainly happen in one of two places:

* Upon save of a document, the server can validate the mobiledoc to confirm there is nothing unsafe or escape content that may be unsafe.
* Upon rendering of a document, hrefs should be treated as un-trusted and escaped.

I think the [mobiledoc-dom-renderer](https://github.com/bustlelabs/mobiledoc-dom-renderer) should treat href as untrusted by default, and escape them. Perhaps this option can be configurable.

@YoranBrondsema if you want to upstream some work securing the dom and/or [html renderer](https://github.com/bustlelabs/mobiledoc-html-renderer) I would be happy to help it along. If you want to patch an immediate issue, I might suggest creating a [markupElementRenderer](https://github.com/bustlelabs/mobiledoc-dom-renderer#markupelementrenderer) that secures `href`.

**Comment by YoranBrondsema** [comment]
> Upon rendering of a document, hrefs should be treated as un-trusted and escaped.
I will work on a fix in [mobiledoc-dom-renderer](https://github.com/bustlelabs/mobiledoc-dom-renderer) for that tonight and let you know how it goes.

> Upon save of a document, the server can validate the mobiledoc to confirm there is nothing unsafe or escape content that may be unsafe.
I agree that this should happen but it requires the server to be able to parse Mobiledoc. This means that if your backend does not run Javascript, you have to write your own Mobiledoc parser. Therefore, I think it's better if sanitization happens in the client, in `mobiledoc-kit`, and that the Mobiledoc generated by the editor should always be sanitized. However, I'm not sure if this is too strict; I can't think of cases right now but maybe in some rare cases you do want to have "unfiltered" Mobiledoc?

**Comment by joshfrench** [comment]
One vote for configurable/opt-out. One of the reasons we dropped our previous editor was that we couldn't disable sanitization. For in-house applications where I generally trust the source of content, I'd prefer the flexibility to do weird things when we have to.
