### ISSUE TITLE
API for setting initial cursor position?

### ISSUE THREAD

**Issue by mysterlune** [bustlelabs/mobiledoc-kit#526]
It is unclear how, when a post has content and an editor enters "isEditable" mode, how to set the initial cursor position.

I see in the `... cursor.js` code there is an API for `selectRange(...)`, which is pretty cool as I can programmatically create selections in an editable post... However, I'd like to also be able to programmatically set the cursor position...

Does this mean that I should be using `editor.cursor.selectRange()` with a collapsed range in order to set the cursor position?

I'm just trying to clarify, and would be willing to create some documentation about this if it turns out that this is the right API usage for the functionality I'm looking for.

**Comment by bantic** [comment]
@mysterlune Thanks for the question! Your instinct is absolutely right here: Setting a range that is collapsed (headPosition equals tailsPosition) will move the cursor to that spot. When creating a range the tailPosition is optional and defaults to the headPosition's value, so you would create one like so:

```javascript
let headPosition = ...;
let rangeToSelect = new MobiledocKit.Range(headPosition);
// or, equivalent:
// let rangeToSelect = new MobiledocKit.Range(headPosition, headPosition); 
editor.selectRange(rangeToSelect);
```

**Comment by mixonic** [comment]
The API I strongly suggest you use for the above is:

```js
let headPosition = ...;
let rangeToSelect = headPosition.toRange();
// or, equivalent:
// let rangeToSelect = headPosition.toRange(headPosition);
editor.selectRange(rangeToSelect); 
```

**Comment by knownasilya** [comment]
On a similar note, how would I get the position for the start and end of an atom?

```js
let atom = editor.insertAtom('my-atom', '...');
let range = atom.section.toRange(); // seems to give a bigger range then I expect, like the whole line.
```
