### ISSUE TITLE
Chore: Add slack channel

### ISSUE THREAD

**Issue by bantic** [bustlelabs/mobiledoc-kit#529]
We will add a slack channel for coordination especially wrt #429

**Comment by bantic** [comment]
@disordinary Made one, with a temporary invite link: https://mobiledoc-kit.slack.com/shared_invite/MTQwMTI1MTQ3NDEyLTE0ODY3NTY5OTYtMzdiMmU4MThiMA
We still need to set up a permanent slack-in URL, and then update the README

**Comment by disordinary** [comment]
I created a slackin app and updated the readme. 

For reference the slackin app is located here: https://mobiledoc-slack.herokuapp.com/

I'll close this issue. 😄
