### ISSUE TITLE
Placeholder doesn't do anything

### ISSUE THREAD

**Issue by knownasilya** [bustlelabs/mobiledoc-kit#546]
Example https://ember-twiddle.com/c41e57f02ed05fb966cbc984d0a23168?openFiles=components.my-editor-wrapper.js%2Ctemplates.components.my-editor-wrapper.hbs

Basically, when creating an `Editor` and setting the `placeholder` to a string, it doesn't show up anywhere. At first, I thought this was related to #511, but it isn't as far as I can tell.

**Comment by disordinary** [comment]
The placeholder is simply a data attribute, it needs psuedo element to display anything, see:
https://github.com/bustlelabs/mobiledoc-kit/blob/master/src/css/mobiledoc-kit.css#L23

**Comment by disordinary** [comment]
Hey @knownasilya,

I'm closing this issue, but please feel free to comment on this or message me in the mobiledoc slack if you still have questions.

**Comment by knownasilya** [comment]
This should probably be a note in the documentation (with the example css), since it's not so obvious.

**Comment by disordinary** [comment]
Yep, 

I think the intention is for people to use the mobiledoc css in their projects, we don't and had to figure this out as well.
