### ISSUE TITLE
Scroll does not follow cursor when typing or moving caret

### ISSUE THREAD

**Issue by mernen** [bustlelabs/mobiledoc-kit#558]
Steps:

1. Open the demo page (https://bustlelabs.github.io/mobiledoc-kit/demo/), click the first demo
2. Press Enter until the content becomes taller than the container
3. Type anything
4. Press left/right arrow to move cursor

Expected: as soon as the cursor had moved outside of visible area (after the 5th Enter here), the container should have scrolled. Steps 3 and 4 should be completely in view.

Actual: container scroll is never adjusted, editing is completely blindfolded. (It does properly scroll if you use up/down arrow keys, though)

**Comment by disordinary** [comment]
Hey @mernen, 

At this stage it's up to the editor that is created with mobiledoc-kit to handle the scrolling. You can do it pretty easily by adding a callback to the` editor.cursorDidChange` event and then checking if the `boundingClientRect` of the range is on screen or not.

There's some more information here: https://developer.mozilla.org/en-US/docs/Web/API/Range/getBoundingClientRect

I've found that `getBoundingClientRect` is pretty buggy in Safari when the range is collapsed so it can be better to simply get the clientRects if you're not worried about the width and height of the selection.
