### ISSUE TITLE
Rendering cards inside contenteditable=false div?

### ISSUE THREAD

**Issue by abuiles** [bustlelabs/mobiledoc-kit#559]
I noticed a weird behavior when rendering cards. Since the outer div containing the card is part of the "contenteditable" element, if you put the cursor in the line right before the actual card, it looks like you can type, but if you type, nothing gets render! See the following gif 

http://s.abuiles.com/3m0s0J1h1L3T

Is this a bug or intended behavior?

**Comment by disordinary** [comment]
Hey @abuiles,

I agree it's a little confusing, the last editor that I was working on with mobiledoc-kit we did quite a bit of work trying to find a better paradigm for card selection.

The way it's supposed to work with mobiledoc-kit is that the card is `inline-block` you can see it in the CSS which is bundled with the project https://github.com/bustlelabs/mobiledoc-kit/blob/master/src/css/mobiledoc-kit.css#L70

So, the cursor is supposed to sit either side of the card and not above or below it.

**Comment by abuiles** [comment]
@disordinary thanks! I forgot to include the CSS  :). That work around  works for me :).
